name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install server dependencies
      working-directory: ./server
      run: npm install

    - name: Build server
      working-directory: ./server
      run: npm run dev

    - name: Set up Node.js for client
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    - name: Build client
      working-directory: ./client
      run: npm start

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'
        APPLICATION_NAME: 'your-application-name'
        ENVIRONMENT_NAME: 'your-environment-name'
      run: |
        cd server
        zip -r ../deploy.zip *
        cd ../client
        zip -r ../deploy.zip build
        aws s3 cp ../deploy.zip s3://elasticbeanstalk-us-east-1-637423648684/deploy.zip
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=yelasticbeanstalk-us-east-1-637423648684,S3Key=deploy.zip
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
